<template>
  <CaseStudiesHeaderType2
    :title="$t('case_studies.lilienthal.heading.title')"
    :header-info="$t('case_studies.lilienthal.heading.text')"
    :scroll-path-id="$t('case_studies.lilienthal.heading.scrollPathId')"
    company="Lilienthal"
  >
    <template #header-services>
      <CommonHeadingServices
        :text1="$t('case_studies.sektor.heading.service')"
        :text2="$t('case_studies.lilienthal.heading.marketing')"
        :subtext1="$t('case_studies.sektor.heading.industry')"
        :subtext2="$t('case_studies.lilienthal.heading.stairlifts')"
        :subtext3="$t('case_studies.sektor.heading.goal')"
        :subtext4="$t('case_studies.lilienthal.heading.goal_text')"
      />
    </template>
  </CaseStudiesHeaderType2>
</template>
